name: Update README 1

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-lastest
    name: Update Profile README

    steps:
      - uses: actions/checkout@2.3.4

      - uses: Readme-Workflows/recent-activity@2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
