name: Update README 1

on:
  schedule:
    - cron: '0 */12 * * *'
    

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update README with recent activity
        uses: wildchamo/wildchamo # Reemplaza con tu información
